# Generated by Django 4.2.8 on 2023-12-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
