# Generated by Django 4.2.8 on 2023-12-17 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_driver_lat_driver_lon'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='status',
            field=models.FloatField(choices=[(True, 'Свободен'), (False, 'В пути'), (False, 'Не на рейсе')], default=False, verbose_name='Статус'),
        ),
    ]
