# Generated by Django 4.2.8 on 2023-12-17 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_driver_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='status',
            field=models.IntegerField(choices=[(1, 'В пути'), (2, 'Свободен'), (3, 'Не на линии')], default=2, verbose_name='Статус'),
        ),
    ]
