# Generated by Django 4.2.8 on 2024-01-11 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0005_alter_driver_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auto',
            old_name='tariff',
            new_name='name',
        ),
    ]
