# Generated by Django 4.2.8 on 2024-01-11 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0006_rename_tariff_auto_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Auto',
            new_name='Tariff',
        ),
    ]
