# Generated by Django 5.0.1 on 2024-01-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0008_alter_driver_options_driver_name_driver_number_auto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='number_auto',
            field=models.CharField(max_length=20, verbose_name='Регистрационный номер автомобиля'),
        ),
    ]
