# Generated by Django 5.0.1 on 2024-01-31 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0010_alter_driver_lat_alter_driver_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='lat',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='lon',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Долгота'),
        ),
    ]
