# Generated by Django 5.0.1 on 2024-02-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0011_alter_driver_lat_alter_driver_lon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='name',
        ),
        migrations.AddField(
            model_name='driver',
            name='city',
            field=models.CharField(choices=[('Бишкек', 'Бишкек'), ('Баткен', 'Баткен'), ('Джалал-Абад', 'Джалал-Абад'), ('Кара-Балта', 'Кара-Балта'), ('Каракол', 'Каракол'), ('Нарын', 'Нарын'), ('Ош', 'Ош'), ('Токмок', 'Токмок'), ('Узген', 'Узген')], default=1, verbose_name='Город'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='driver',
            name='issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='Когда выдано'),
        ),
        migrations.AddField(
            model_name='driver',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='driver',
            name='lisence_country',
            field=models.CharField(blank=True, choices=[('Азербайджан', 'Азербайджан'), ('Армения', 'Армения'), ('Беларусь', 'Беларусь'), ('Грузия', 'Грузия'), ('Замбия', 'Замбия'), ('Казахстан', 'Казахстан'), ('Камерун', 'Камерун'), ('Кыргызстан', 'Кыргызстан'), ('Латвия', 'Латвия'), ('Литва', 'Литва'), ('Молдова', 'Молдова'), ('Норвегия', 'Норвегия'), ('Реюьон', 'Реюьон'), ('Российская Федерация', 'Российская Федерация'), ('Сербия', 'Сербия'), ('Таджикистан', 'Таджикистан'), ('Узбекистан', 'Узбекистан'), ('Украина', 'Украина'), ('Финляндия', 'Финляндия'), ('Франция', 'Франция'), ('Эстония', 'Эстония')], max_length=200, null=True, verbose_name='Страна получения ВУ'),
        ),
        migrations.AddField(
            model_name='driver',
            name='lisence_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер ВУ'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='star',
            field=models.IntegerField(blank=True, null=True, verbose_name='Оценки водителя'),
        ),
    ]
