# Generated by Django 5.0.1 on 2024-02-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0012_remove_driver_name_driver_city_driver_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='total_star',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
