# Generated by Django 5.0.1 on 2024-02-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0013_driver_total_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='star',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Оценки водителя'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='total_star',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
