# Generated by Django 5.0.1 on 2024-02-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0014_alter_driver_star_alter_driver_total_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='users_star',
            field=models.IntegerField(blank=True, null=True, verbose_name='Кол-во пользователей которые оставили отзыв'),
        ),
    ]
