# Generated by Django 5.0.1 on 2024-02-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0015_driver_users_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='star',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Оценки водителя'),
        ),
    ]
