# Generated by Django 5.0.1 on 2024-02-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0016_alter_driver_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='total_star',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='driver',
            name='users_star',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
