# Generated by Django 4.2.8 on 2023-12-16 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poit_a', models.CharField(max_length=255, verbose_name='Точка А')),
                ('poit_b', models.CharField(max_length=255, verbose_name='Точка B')),
                ('time_start', models.DateTimeField(verbose_name='Время начала')),
                ('time_end', models.DateTimeField(verbose_name='Время окончания')),
                ('total_cost', models.IntegerField(verbose_name='Общая стоимость')),
                ('payment_type', models.CharField(choices=[('Наличные', 'Наличные'), ('С картой', 'С картой')], max_length=8, verbose_name='Тип оплаты')),
                ('route', models.ImageField(upload_to='routes/%Y/%m/%d/', verbose_name='Маршрут поездки')),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='drivers.driver', verbose_name='Водитель')),
            ],
            options={
                'verbose_name': 'Поездка',
                'verbose_name_plural': 'Поездки',
            },
        ),
    ]
