# Generated by Django 5.0.1 on 2024-01-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Принятый заказ',
                'verbose_name_plural': 'Принятые заказы',
            },
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poit_a', models.CharField(max_length=255, verbose_name='Точка А')),
                ('poit_b', models.CharField(max_length=255, verbose_name='Точка B')),
                ('total_cost', models.IntegerField(verbose_name='Общая стоимость')),
                ('payment_type', models.CharField(choices=[('1', 'Наличные'), ('2', 'С картой')], max_length=8, verbose_name='Тип оплаты')),
            ],
            options={
                'verbose_name': 'Вызов',
                'verbose_name_plural': 'Вызовы',
            },
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poit_a', models.CharField(max_length=255, verbose_name='Точка А')),
                ('poit_b', models.CharField(max_length=255, verbose_name='Точка B')),
                ('time_start', models.DateTimeField(auto_now_add=True, verbose_name='Время начала')),
                ('time_end', models.DateTimeField(verbose_name='Время окончания')),
                ('total_cost', models.IntegerField(verbose_name='Общая стоимость')),
                ('payment_type', models.CharField(choices=[('1', 'Наличные'), ('2', 'С картой')], max_length=8, verbose_name='Тип оплаты')),
                ('route', models.ImageField(blank=True, upload_to='routes/%Y/%m/%d/', verbose_name='Маршрут поездки')),
            ],
            options={
                'verbose_name': 'Поездка',
                'verbose_name_plural': 'Поездки',
            },
        ),
    ]
