# Generated by Django 5.0.1 on 2024-01-26 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0008_alter_driver_options_driver_name_driver_number_auto_and_more'),
        ('rental', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptcall',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='call',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пассажир'),
        ),
        migrations.AddField(
            model_name='acceptcall',
            name='call',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.call'),
        ),
        migrations.AddField(
            model_name='rental',
            name='driver',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='drivers.driver', verbose_name='Водитель'),
        ),
        migrations.AddField(
            model_name='rental',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пассажир'),
        ),
    ]
