# Generated by Django 5.0.1 on 2024-01-27 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='passenger',
        ),
        migrations.AddField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('waiting', 'Ожидание'), ('accept', 'Принято'), ('done', 'Доехали'), ('cancel', 'Отмена')], default='waiting', max_length=100, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='driver',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='rentals_as_driver', to=settings.AUTH_USER_MODEL, verbose_name='Водитель'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals_as_passenger', to=settings.AUTH_USER_MODEL, verbose_name='Пассажир'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='time_end',
            field=models.DateTimeField(blank=True, verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='time_start',
            field=models.DateTimeField(blank=True, verbose_name='Время начала'),
        ),
        migrations.DeleteModel(
            name='AcceptCall',
        ),
        migrations.DeleteModel(
            name='Call',
        ),
    ]
