# Generated by Django 5.0.1 on 2024-01-27 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_remove_call_passenger_rental_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('waiting', 'Ожидание'), ('accept', 'Принято'), ('ride', 'Поехали'), ('done', 'Доехали'), ('cancel', 'Отмена')], default='waiting', max_length=100, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='time_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='time_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время начала'),
        ),
    ]
