# Generated by Django 5.0.1 on 2024-01-28 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0008_alter_driver_options_driver_name_driver_number_auto_and_more'),
        ('rental', '0005_alter_rental_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rentals_as_driver', to='drivers.driver', verbose_name='Водитель'),
        ),
    ]
