# Generated by Django 5.0.1 on 2024-01-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0006_alter_rental_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('request', 'Запрос такси'), ('c', 'Водитель принял'), ('driver-en-route', 'Водитель в пути'), ('on-the-way', 'В пути'), ('completed', 'Завершено'), ('cancelled', 'Отменено')], default='request', max_length=100, verbose_name='Статус'),
        ),
    ]
