# Generated by Django 5.0.1 on 2024-01-29 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0008_alter_driver_options_driver_name_driver_number_auto_and_more'),
        ('rental', '0007_alter_rental_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='poit_a',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='poit_b',
        ),
        migrations.AddField(
            model_name='rental',
            name='lat_b',
            field=models.CharField(default=1, max_length=255, verbose_name='Широта Б'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rental',
            name='lon_a',
            field=models.CharField(default=1, max_length=255, verbose_name='Долгота А'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rental',
            name='lon_b',
            field=models.CharField(default=1, max_length=255, verbose_name='Долгота Б'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rental',
            name='poit_a_street',
            field=models.CharField(default=1, max_length=255, verbose_name='Улица А'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rental',
            name='poit_b_street',
            field=models.CharField(default=1, max_length=255, verbose_name='Улица Б'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rental',
            name='tarif',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='drivers.tariff', verbose_name='Тариф'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('request', 'Запрос такси'), ('driver-accepted', 'Водитель принял'), ('driver-en-route', 'Водитель в пути'), ('on-the-way', 'В пути'), ('completed', 'Завершено'), ('cancelled', 'Отменено')], default='request', max_length=100, verbose_name='Статус'),
        ),
    ]
