# Generated by Django 5.0.1 on 2024-01-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0008_remove_rental_poit_a_remove_rental_poit_b_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='lat_a',
            field=models.CharField(default=1, max_length=255, verbose_name='Широта B'),
            preserve_default=False,
        ),
    ]
