# Generated by Django 5.0.1 on 2024-01-29 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0009_rental_lat_a'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental',
            old_name='poit_a_street',
            new_name='point_a_street',
        ),
        migrations.RenameField(
            model_name='rental',
            old_name='poit_b_street',
            new_name='point_b_street',
        ),
    ]
