# Generated by Django 5.0.1 on 2024-01-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0010_rename_poit_a_street_rental_point_a_street_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='lon_b',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Долгота Б'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='point_b_street',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Улица Б'),
        ),
    ]
