# Generated by Django 5.0.1 on 2024-01-31 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0012_alter_rental_lat_b'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='lat_a',
            field=models.CharField(max_length=255, verbose_name='Широта А'),
        ),
    ]
