# Generated by Django 5.0.1 on 2024-02-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0013_alter_rental_lat_a'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('request', 'Запрос такси'), ('driver-accepted', 'Водитель принял'), ('driver-waiting', 'Водитель ждет'), ('on-the-way', 'В пути'), ('completed', 'Завершено'), ('cancelled', 'Отменено')], default='request', max_length=100, verbose_name='Статус'),
        ),
    ]
