# Generated by Django 5.0.1 on 2024-01-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'Клиент'), (2, 'Таксист')], default=1, verbose_name='Статус'),
        ),
    ]
