# Generated by Django 5.0.1 on 2024-01-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Клиент'), ('driver', 'Таксист')], default='customer', verbose_name='Статус'),
        ),
    ]
